from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from .validators import get_candidate_image_path, get_flag_image_path, image_validate

ALLOWED_IMAGE_EXTENSIONS=['jpg', 'png', 'jpeg', 'webp','svg']

class Candidate(models.Model):

    name = models.CharField(max_length=255)
    bio = models.TextField()
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, editable=False, null=True, blank=True)
    image = models.ImageField(upload_to=get_candidate_image_path, null=True, blank=True, validators=[FileExtensionValidator(allowed_extensions=ALLOWED_IMAGE_EXTENSIONS), image_validate])

    def __str__(self):
        return self.name

class Party(models.Model):
    name = models.CharField(max_length=100, unique=True)
    info = models.TextField(blank=True, null=True)
    flag = models.ImageField(upload_to=get_flag_image_path, null=True, blank=True, validators=[FileExtensionValidator(allowed_extensions=ALLOWED_IMAGE_EXTENSIONS), image_validate])

    def __str__(self):
        return self.name

class KartutType(models.TextChoices):
    ALLEGATION = 'allegation', 'Allegation'
    GOOD_WORK = 'goodwork', 'Good Work'
    BAD_WORK = 'badwork', 'Bad Work'


class Kartut(models.Model):

    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, null=True,blank=True)
    party = models.ForeignKey(Party, on_delete=models.CASCADE, null=True,blank=True)
    kartut_type = models.CharField(max_length=20, choices=KartutType.choices)
    info = models.TextField()
    kartuts_date = models.DateField()
    source1 = models.URLField(blank=False, null=False)
    source2 = models.URLField(blank=True, null=True)
    source3 = models.URLField(blank=True, null=True)
    source4 = models.URLField(blank=True, null=True)


class CaseType(models.TextChoices):
    FINANCIAL = 'financial', 'Financial'
    SERIOUS = 'serious', 'Serious'
    OTHER = 'other', 'Other'

class Courts(models.TextChoices):
    SPECIAL_COURT = 'specialcourt', 'बिशेष अदालत'
    BIRATNAGAR_HC = 'biratnagarhc', 'उच्च अदालत विराटनगर'
    ILAM_HC = 'illamhc', 'उच्च अदालत विराटनगर, इलाम इजलास'
    DHANKUTA_HC = 'dhankutahc', 'उच्च अदालत विराटनगर, धनकुटा इजलास'
    OKHALDHUNGA_HC = 'okhaldhungahc', 'उच्च अदालत विराटनगर, अस्थायी इजलास ओखलढुंगा'
    JANAKPUR_HC = 'janakpurhc', 'उच्च अदालत जनकपुर'
    RAJBIRAJ_HC = 'rajbirajhc', 'उच्च अदालत जनकपुर, राजविराज इजलास'
    BIRGANJ_HC = 'birganjhc', 'उच्च अदालत जनकपुर, अस्थायी इजलास वीरगन्ज'
    PATAN_HC = 'patanhc', 'उच्च अदालत पाटन'
    HETAUDA_HC = 'hetaudahc', 'उच्च अदालत पाटन, हेटौंडा इजलास'
    POKHARA_HC = 'pokharahc', 'उच्च अदालत पोखरा'
    BAGLUNG_HC = 'baglunghc', 'उच्च अदालत पोखरा, बागलुङ इजलास'
    TULSIPUR_HC = 'tulsipurhc', 'उच्च अदालत तुलसीपुर'
    BUTWAL_HC = 'butwalhc', 'उच्च अदालत तुलसीपुर, बुटवल इजलास'
    NEPALGUNJ_HC = 'nepalgunjhc', 'उच्च अदालत तुलसीपुर, नेपालगंज इजलास'
    SURKHET_HC = 'surkhethc', 'उच्च अदालत सुर्खेत'
    JUMLA_HC = 'jumlahc', 'उच्च अदालत सुर्खेत, जुम्ला इजलास'
    DIPAYAL_HC = 'dipayalhc', 'उच्च अदालत दिपायल'
    MAHENDRANAGAR_HC = 'mahendranagarhc', 'उच्च अदालत दिपायल, महेन्द्रनगर इजलास'
    ACHHAM_DC = 'achhamdc', 'अछाम जिल्ला अदालत'
    ARGAKHANCHI_DC = 'argakhanchidc', 'अर्घाखाँची जिल्ला अदालत'
    ILAM_DC = 'ilamdc', 'इलाम जिल्ला अदालत'
    UDAYAPUR_DC = 'udayapurdc', 'उदयपुर जिल्ला अदालत'
    OKHALDHUNGA_DC = 'okhaldhungadc', 'ओखलढुंगा जिल्ला अदालत'
    KANCHANPUR_DC = 'kanchanpurdc', 'कन्चनपुर जिल्ला अदालत'
    KAPILBASTU_DC = 'kapilbastudc', 'कपिलवस्तु जिल्ला अदालत'
    KATHMANDU_DC = 'kathmandudc','काठमाडौं जिल्ला अदालत'
    KAVREPALANCHOWK_DC = 'kavrepalanchowkdc', 'काभ्रेपलान्चोक जिल्ला अदालत'
    KALIKOT_DC = 'kalikotdc', 'कालिकोट जिल्ला अदालत'
    KASKI_DC = 'kaskidc', 'कास्की जिल्ला अदालत'
    KAILALI_DC = 'kailalidc', 'कैलाली जिल्ला अदालत'
    KHOTANG_DC = 'khotangdc', 'खोटाङ जिल्ला अदालत'
    GULMI_DC = 'gulmidc', 'गुल्मी जिल्ला अदालत'
    GORKHA_DC = 'gorkhadc', 'गोरखा जिल्ला अदालत'
    CHITWAN_DC = 'chitwandc', 'चितवन जिल्ला अदालत'
    JAJARKOT_DC = 'jajarkotdc', 'जाजरकोट जिल्ला अदालत'
    JUMLA_DC = 'jumladc', 'जुम्ला जिल्ला अदालत'
    JHAPA_DC = 'jhapadc', 'झापा जिल्ला अदालत'
    DADELDHURA_DC = 'dadeldhuradc', 'डडेलधुरा जिल्ला अदालत'
    DOTI_DC = 'dotidc', 'डोटी जिल्ला अदालत'
    DOLPA_DC = 'dolpadc', 'डोल्पा जिल्ला अदालत'
    TANAHUN_DC = 'tanahundc', 'तनहुँ जिल्ला अदालत'
    TAPLEJUNG_DC = 'taplejungdc', 'ताप्लेजुङ जिल्ला अदालत'
    THERATHUM_DC = 'therathumdc', 'तेह्रथुम जिल्ला अदालत'
    DANG_DC = 'dangdc', 'दाङ जिल्ला अदालत'
    DARCHULA_DC = 'darchuladc', 'दार्चुला जिल्ला अदालत'
    DAILEKH_DC = 'dailekhdc', 'दैलेख जिल्ला अदालत'
    DOLAKHA_DC = 'dolakhadc', 'दोलखा जिल्ला अदालत'
    DHANKUTA_DC = 'dhankutadc', 'धनकुटा जिल्ला अदालत'
    DHANUSA_DC = 'dhanusadc', 'धनुषा जिल्ला अदालत'
    DHADING_DC = 'dhadhingdc', 'धादिङ जिल्ला अदालत'
    NAWALPARASI_DC = 'nawalparasidc', 'नवलपरासी जिल्ला अदालत'
    NUWAKOT_DC = 'nuwakotdc', 'नुवाकोट जिल्ला अदालत'
    PARBAT_DC = 'parbatdc', 'पर्वत जिल्ला अदालत'
    PARSA_DC = 'parsadc', 'पर्सा जिल्ला अदालत'
    PANCHTHAR_DC = 'panchthardc', 'पाँचथर जिल्ला अदालत'
    PALPA_DC = 'palpadc', 'पाल्पा जिल्ला अदालत'
    PYUTHAN_DC = 'pyuthandc', 'प्युठान जिल्ला अदालत'
    BAJHANG_DC = 'bajhangdc', 'बाज्हाङ जिल्ला अदालत'
    BARDIYA_DC = 'bardiyadc', 'बर्दिया जिल्ला अदालत'
    BANKE_DC = 'bankedc', 'बाँके जिल्ला अदालत'
    BAGLUNG_DC = 'baglungdc', 'बागलुङ जिल्ला अदालत'
    BAJURA_DC = 'bajuradc', 'बाजुरा जिल्ला अदालत'
    BARA_DC = 'baradc', 'बारा जिल्ला अदालत'
    BAITADI_DC = 'baitadidc', 'बैतडी जिल्ला अदालत'
    BHAKTAPUR_DC = 'bhaktapurdc', 'भक्तपुर जिल्ला अदालत'
    BHOJPUR_DC = 'bhojpurdc', 'भोजपुर जिल्ला अदालत'
    MAKWANPUR_DC = 'makwanpurdc', 'मकवानपुर जिल्ला अदालत'
    MANANG_DC = 'manangdc', 'मनांङ जिल्ला अदालत'
    MAHOTTARI_DC = 'mahottaridc', 'महोत्तरी जिल्ला अदालत'
    MUGU_DC = 'mugudc', 'मुगु जिल्ला अदालत'
    MUSTANG_DC = 'mustangdc', 'मुस्तांङ जिल्ला अदालत'
    MORANG_DC = 'morangdc', 'मोरङ जिल्ला अदालत'
    MYAGDI_DC = 'myagdidc', 'म्याग्दी जिल्ला अदालत'
    RASUWA_DC = 'rasuwadc', 'रसुवा जिल्ला अदालत'
    RAMECHAP_DC = 'ramechapdc', 'रामेछाप जिल्ला अदालत'
    RUKUM_DC = 'rukumdc', 'रुकुम जिल्ला अदालत'
    RUPANDEHI_DC = 'rupandehidc', 'रूपन्देही जिल्ला अदालत'
    ROLPA_DC = 'rolpadc', 'रोल्पा जिल्ला अदालत'
    RAUTAHAT_DC = 'rautahatdc', 'रौतहट जिल्ला अदालत'
    LAMJUNG_DC = 'lamjungdc', 'लमजुङ जिल्ला अदालत'
    LALITPUR_DC = 'lalitpurdc', 'ललितपुर जिल्ला अदालत'
    SANKHUWASABHA_DC = 'sankhuwasabhadc', 'संखुवासभा जिल्ला अदालत'
    SAPTARI_DC = 'saptaridc', 'सप्तरी जिल्ला अदालत'
    SARLAHI_DC = 'sarlahidc', 'सर्लाही जिल्ला अदालत'
    SALYAN_DC = 'salyandc', 'सल्यान जिल्ला अदालत'
    SINDHUPALCHOWK_DC = 'sindhupalchowkdc', 'सिन्धुपाल्चोक जिल्ला अदालत'
    SINDHULI_DC = 'sindhulidc', 'सिन्धुली जिल्ला अदालत'
    SIRAHA_DC = 'sirahadc', 'सिराहा जिल्ला अदालत'
    SUNSARI_DC = 'sunsaridc', 'सुनसरी जिल्ला अदालत'
    SURKHET_DC = 'surkhetdc', 'सुर्खेत जिल्ला अदालत'
    SOLUKHUMBU_DC = 'solukhumbudc', 'सोलुखुम्बु जिल्ला अदालत'
    SYANGJA_DC = 'syangjyadc', 'स्याङजा जिल्ला अदालत'
    HUMLA_DC = 'humladc', 'हुम्ला जिल्ला अदालत'
    NAWALPUR_DC = 'nawalpurdc', 'नवलपुर जिल्ला अदालत'
    RUKUMKOT_DC = 'rukumkotdc', 'रुकुमकोट जिल्ला अदालत'

class Case(models.Model):

    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, null=True)
    info = models.CharField(max_length=255)
    case_type = models.CharField(max_length=20, choices=CaseType.choices)
    court = models.CharField(max_length=30, choices=Courts.choices)
    case_number = models.CharField(max_length=100)
    date_filed = models.DateField()
    pending = models.BooleanField(default=True)
    guilty = models.BooleanField(default=False)


class HoR_Constituency(models.TextChoices):
    TAPLEJUNG_1 = 'TAPLEJUNG_1'
    PANCHTHAR_1 = 'PANCHTHAR_1'
    ILLAM_1 = 'ILLAM_1'
    ILLAM_2 = 'ILLAM_2'
    JHAPA_1 = 'JHAPA_1'
    JHAPA_2 = 'JHAPA_2'
    JHAPA_3 = 'JHAPA_3'
    JHAPA_4 = 'JHAPA_4'
    JHAPA_5 = 'JHAPA_5'
    SANKHUWASABHA_1 = 'SANKHUWASABHA_1'
    TEHRATHUM_1 = 'TEHRATHUM_1'
    BHOJPUR_1 = 'BHOJPUR_1'
    DHANKUTA_1 = 'DHANKUTA_1'
    MORANG_1 = 'MORANG_1'
    MORANG_2 = 'MORANG_2'
    MORANG_3 = 'MORANG_3'
    MORANG_4 = 'MORANG_4'
    MORANG_5 = 'MORANG_5'
    MORANG_6 = 'MORANG_6'
    SUNSARI_1 = 'SUNSARI_1'
    SUNSARI_2 = 'SUNSARI_2'
    SUNSARI_3 = 'SUNSARI_3'
    SUNSARI_4 = 'SUNSARI_4'
    SOLUKHUMBU_1 = 'SOLUKHUMBU_1'
    KHOTANG_1 = 'KHOTANG_1'
    OKHALDHUNGA_1 = 'OKHALDHUNGA_1'
    UDAYAPUR_1 = 'UDAYAPUR_1'
    UDAYAPUR_2 = 'UDAYAPUR_2'
    SAPTARI_1 = 'SAPTARI_1'
    SAPTARI_2 = 'SAPTARI_2'
    SAPTARI_3 = 'SAPTARI_3'
    SAPTARI_4 = 'SAPTARI_4'
    SIRAHA_1 = 'SIRAHA_1'
    SIRAHA_2 = 'SIRAHA_2'
    SIRAHA_3 = 'SIRAHA_3'
    SIRAHA_4 = 'SIRAHA_4'
    DHANUSA_1 = 'DHANUSA_1'
    DHANUSA_2 = 'DHANUSA_2'
    DHANUSA_3 = 'DHANUSA_3'
    DHANUSA_4 = 'DHANUSA_4'
    MAHOTTARI_1 = 'MAHOTTARI_1'
    MAHOTTARI_2 = 'MAHOTTARI_2'
    MAHOTTARI_3 = 'MAHOTTARI_3'
    MAHOTTARI_4 = 'MAHOTTARI_4'
    SARLAHI_1 = 'SARLAHI_1'
    SARLAHI_2 = 'SARLAHI_2'
    SARLAHI_3 = 'SARLAHI_3'
    SARLAHI_4 = 'SARLAHI_4'
    RAUTAHAT_1 = 'RAUTAHAT_1'
    RAUTAHAT_2 = 'RAUTAHAT_2'
    RAUTAHAT_3 = 'RAUTAHAT_3'
    RAUTAHAT_4 = 'RAUTAHAT_4'
    BARA_1 = 'BARA_1'
    BARA_2 = 'BARA_2'
    BARA_3 = 'BARA_3'
    BARA_4 = 'BARA_4'
    PARSA_1 = 'PARSA_1'
    PARSA_2 = 'PARSA_2'
    PARSA_3 = 'PARSA_3'
    PARSA_4 = 'PARSA_4'
    DOLAKHA_1 = 'DOLAKHA_1'
    RAMECHHAP_1 = 'RAMECHHAP_1'
    SINDHULI_1 = 'SINDHULI_1'
    SINDHULI_2 = 'SINDHULI_2'
    RASUWA_1 = 'RASUWA_1'
    DHADING_1 = 'DHADING_1'
    DHADING_2 = 'DHADING_2'
    NUWAKOT_1 = 'NUWAKOT_1'
    NUWAKOT_2 = 'NUWAKOT_2'
    KATHMANDU_1 = 'KATHMANDU_1'
    KATHMANDU_2 = 'KATHMANDU_2'
    KATHMANDU_3 = 'KATHMANDU_3'
    KATHMANDU_4 = 'KATHMANDU_4'
    KATHMANDU_5 = 'KATHMANDU_5'
    KATHMANDU_6 = 'KATHMANDU_6'
    KATHMANDU_7 = 'KATHMANDU_7'
    KATHMANDU_8 = 'KATHMANDU_8'
    KATHMANDU_9 = 'KATHMANDU_9'
    KATHMANDU_10 = 'KATHMANDU_10'
    BHAKTAPUR_1 = 'BHAKTAPUR_1'
    BHAKTAPUR_2 = 'BHAKTAPUR_2'
    LALITPUR_1 = 'LALITPUR_1'
    LALITPUR_2 = 'LALITPUR_2'
    LALITPUR_3 = 'LALITPUR_3'
    KAVREPALANCHOWK_1 = 'KAVREPALANCHOWK_1'
    KAVREPALANCHOWK_2 = 'KAVREPALANCHOWK_2'
    SINDHUPALCHOWK_1 = 'SINDHUPALCHOWK_1'
    SINDHUPALCHOWK_2 = 'SINDHUPALCHOWK_2'
    MAKWANPUR_1 = 'MAKWANPUR_1'
    MAKWANPUR_2 = 'MAKWANPUR_2'
    CHITWAN_1 = 'CHITWAN_1'
    CHITWAN_2 = 'CHITWAN_2'
    CHITWAN_3 = 'CHITWAN_3'
    GORKHA_1 = 'GORKHA_1'
    GORKHA_2 = 'GORKHA_2'
    MANANG_1 = 'MANANG_1'
    LAMJUNG_1 = 'LAMJUNG_1'
    KASKI_1 = 'KASKI_1'
    KASKI_2 = 'KASKI_2'
    KASKI_3 = 'KASKI_3'
    TANAHUN_1 = 'TANAHUN_1'
    TANAHUN_2 = 'TANAHUN_2'
    SYANGJA_1 = 'SYANGJA_1'
    SYANGJA_2 = 'SYANGJA_2'
    NAWALPARASI_BARDAGHAT_SUSTA_EAST_1 = 'NAWALPARASI_BARDAGHAT_SUSTA_EAST_1'
    NAWALPARASI_BARDAGHAT_SUSTA_EAST_2 = 'NAWALPARASI_BARDAGHAT_SUSTA_EAST_2'
    MUSTANG_1 = 'MUSTANG_1'
    MYAGDI_1 = 'MYAGDI_1'
    BAGLUNG_1 = 'BAGLUNG_1'
    BAGLUNG_2 = 'BAGLUNG_2'
    PARBAT_1 = 'PARBAT_1'
    GULMI_1 = 'GULMI_1'
    GULMI_2 = 'GULMI_2'
    PALPA_1 = 'PALPA_1'
    PALPA_2 = 'PALPA_2'
    ARGHAKHANCHI_1 = 'ARGHAKHANCHI_1'
    NAWALPARASI_BARDAGHAT_SUSTA_WEST_1 = 'NAWALPARASI_BARDAGHAT_SUSTA_WEST_1'
    NAWALPARASI_BARDAGHAT_SUSTA_WEST_2 = 'NAWALPARASI_BARDAGHAT_SUSTA_WEST_2'
    RUPANDEHI_1 = 'RUPANDEHI_1'
    RUPANDEHI_2 = 'RUPANDEHI_2'
    RUPANDEHI_3 = 'RUPANDEHI_3'
    RUPANDEHI_4 = 'RUPANDEHI_4'
    RUPANDEHI_5 = 'RUPANDEHI_5'
    KAPILVASTU_1 = 'KAPILVASTU_1'
    KAPILVASTU_2 = 'KAPILVASTU_2'
    KAPILVASTU_3 = 'KAPILVASTU_3'
    EASTERN_RUKUM_1 = 'EASTERN_RUKUM_1'
    ROLPA_1 = 'ROLPA_1'
    PYUTHAN_1 = 'PYUTHAN_1'
    DANG_1 = 'DANG_1'
    DANG_2 = 'DANG_2'
    DANG_3 = 'DANG_3'
    BANKE_1 = 'BANKE_1'
    BANKE_2 = 'BANKE_2'
    BANKE_3 = 'BANKE_3'
    BARDIYA_1 = 'BARDIYA_1'
    BARDIYA_2 = 'BARDIYA_2'
    SALYAN_1 = 'SALYAN_1'
    DOLPA_1 = 'DOLPA_1'
    MUGU_1 = 'MUGU_1'
    JUMLA_1 = 'JUMLA_1'
    KALIKOT_1 = 'KALIKOT_1'
    HUMLA_1 = 'HUMLA_1'
    JAJARKOT_1 = 'JAJARKOT_1'
    DAILEKH_1 = 'DAILEKH_1'
    DAILEKH_2 = 'DAILEKH_2'
    SURKHET_1 = 'SURKHET_1'
    SURKHET_2 = 'SURKHET_2'
    WESTERN_RUKUM_1 = 'WESTERN_RUKUM_1'
    BAJURA_1 = 'BAJURA_1'
    ACHHAM_1 = 'ACHHAM_1'
    ACHHAM_2 = 'ACHHAM_2'
    BAJHANG_1 = 'BAJHANG_1'
    DOTI_1 = 'DOTI_1'
    KAILALI_1 = 'KAILALI_1'
    KAILALI_2 = 'KAILALI_2'
    KAILALI_3 = 'KAILALI_3'
    KAILALI_4 = 'KAILALI_4'
    KAILALI_5 = 'KAILALI_5'
    DARCHULA_1 = 'DARCHULA_1'
    BAITADI_1 = 'BAITADI_1'
    DADELDHURA_1 = 'DADELDHURA_1'
    KANCHANPUR_1 = 'KANCHANPUR_1'
    KANCHANPUR_2 = 'KANCHANPUR_2'
    KANCHANPUR_3 = 'KANCHANPUR_3'

class Province_Constituency(models.TextChoices):
    TAPLEJUNG_1 = 'TAPLEJUNG_1'
    TAPLEJUNG_2 = 'TAPLEJUNG_2'
    PANCHTHAR_1 = 'PANCHTHAR_1'
    PANCHTHAR_2 = 'PANCHTHAR_2'
    ILLAM_1 = 'ILLAM_1'
    ILLAM_2 = 'ILLAM_2'
    ILLAM_3 = 'ILLAM_3'
    ILAM_4 = 'ILLAM_4'
    JHAPA_1 = 'JHAPA_1'
    JHAPA_2 = 'JHAPA_2'
    JHAPA_3 = 'JHAPA_3'
    JHAPA_4 = 'JHAPA_4'
    JHAPA_5 = 'JHAPA_5'
    JHAPA_6 = 'JHAPA_6'
    JHAPA_7 = 'JHAPA_7'
    JHAPA_8 = 'JHAPA_8'
    JHAPA_9 = 'JHAPA_9'
    JHAPA_10 = 'JHAPA_10'
    SANKHUWASABHA_1 = 'SANKHUWASABHA_1'
    SANKHUWASABHA_2 = 'SANKHUWASABHA_2'
    TEHRATHUM_1 = 'TEHRATHUM_1'
    TEHRATHUM_2 = 'TEHRATHUM_2'
    BHOJPUR_1 = 'BHOJPUR_1'
    BHOJPUR_2 = 'BHOJPUR_2'
    DHANKUTA_1 = 'DHANKUTA_1'
    DHANKUTA_2 = 'DHANKUTA_2'
    MORANG_1 = 'MORANG_1'
    MORANG_2 = 'MORANG_2'
    MORANG_3 = 'MORANG_3'
    MORANG_4 = 'MORANG_4'
    MORANG_5 = 'MORANG_5'
    MORANG_6 = 'MORANG_6'
    MORANG_7 = 'MORANG_7'
    MORANG_8 = 'MORANG_8'
    MORANG_9 = 'MORANG_9'
    MORANG_10 = 'MORANG_10'
    MORANG_11 = 'MORANG_11'
    MORANG_12 = 'MORANG_12'
    SUNSARI_1 = 'SUNSARI_1'
    SUNSARI_2 = 'SUNSARI_2'
    SUNSARI_3 = 'SUNSARI_3'
    SUNSARI_4 = 'SUNSARI_4'
    SUNSARI_5 = 'SUNSARI_5'
    SUNSARI_6 = 'SUNSARI_6'
    SUNSARI_7 = 'SUNSARI_7'
    SUNSARI_8 = 'SUNSARI_8'
    SOLUKHUMBU_1 = 'SOLUKHUMBU_1'
    SOLUKHUMBU_2 = 'SOLUKHUMBU_2'
    KHOTANG_1 = 'KHOTANG_1'
    KHOTANG_2 = 'KHOTANG_2'
    OKHALDHUNGA_1 = 'OKHALDHUNGA_1'
    OKHALDHUNGA_2 = 'OKHALDHUNGA_2'
    UDAYAPUR_1 = 'UDAYAPUR_1'
    UDAYAPUR_2 = 'UDAYAPUR_2'
    UDAYAPUR_3 = 'UDAYAPUR_3'
    UDAYAPUR_4 = 'UDAYAPUR_4'
    SAPTARI_1 = 'SAPTARI_1'
    SAPTARI_2 = 'SAPTARI_2'
    SAPTARI_3 = 'SAPTARI_3'
    SAPTARI_4 = 'SAPTARI_4'
    SAPTARI_5 = 'SAPTARI_5'
    SAPTARI_6 = 'SAPTARI_6'
    SAPTARI_7 = 'SAPTARI_7'
    SAPTARI_8 = 'SAPTARI_8'
    SIRAHA_1 = 'SIRAHA_1'
    SIRAHA_2 = 'SIRAHA_2'
    SIRAHA_3 = 'SIRAHA_3'
    SIRAHA_4 = 'SIRAHA_4'
    SIRAHA_5 = 'SIRAHA_5'
    SIRAHA_6 = 'SIRAHA_6'
    SIRAHA_7 = 'SIRAHA_7'
    SIRAHA_8 = 'SIRAHA_8'
    DHANUSA_1 = 'DHANUSA_1'
    DHANUSA_2 = 'DHANUSA_2'
    DHANUSA_3 = 'DHANUSA_3'
    DHANUSA_4 = 'DHANUSA_4'
    DHANUSA_5 = 'DHANUSA_5'
    DHANUSA_6 = 'DHANUSA_6'
    DHANUSA_7 = 'DHANUSA_7'
    DHANUSA_8 = 'DHANUSA_8'
    MAHOTTARI_1 = 'MAHOTTARI_1'
    MAHOTTARI_2 = 'MAHOTTARI_2'
    MAHOTTARI_3 = 'MAHOTTARI_3'
    MAHOTTARI_4 = 'MAHOTTARI_4'
    MAHOTTARI_5 = 'MAHOTTARI_5'
    MAHOTTARI_6 = 'MAHOTTARI_6'
    MAHOTTARI_7 = 'MAHOTTARI_7'
    MAHOTTARI_8 = 'MAHOTTARI_8'
    SARLAHI_1 = 'SARLAHI_1'
    SARLAHI_2 = 'SARLAHI_2'
    SARLAHI_3 = 'SARLAHI_3'
    SARLAHI_4 = 'SARLAHI_4'
    SARLAHI_5 = 'SARLAHI_5'
    SARLAHI_6 = 'SARLAHI_6'
    SARLAHI_7 = 'SARLAHI_7'
    SARLAHI_8 = 'SARLAHI_8'
    RAUTAHAT_1 = 'RAUTAHAT_1'
    RAUTAHAT_2 = 'RAUTAHAT_2'
    RAUTAHAT_3 = 'RAUTAHAT_3'
    RAUTAHAT_4 = 'RAUTAHAT_4'
    RAUTAHAT_5 = 'RAUTAHAT_5'
    RAUTAHAT_6 = 'RAUTAHAT_6'
    RAUTAHAT_7 = 'RAUTAHAT_7'
    RAUTAHAT_8 = 'RAUTAHAT_8'
    BARA_1 = 'BARA_1'
    BARA_2 = 'BARA_2'
    BARA_3 = 'BARA_3'
    BARA_4 = 'BARA_4'
    BARA_5 = 'BARA_5'
    BARA_6 = 'BARA_6'
    BARA_7 = 'BARA_7'
    BARA_8 = 'BARA_8'
    PARSA_1 = 'PARSA_1'
    PARSA_2 = 'PARSA_2'
    PARSA_3 = 'PARSA_3'
    PARSA_4 = 'PARSA_4'
    PARSA_5 = 'PARSA_5'
    PARSA_6 = 'PARSA_6'
    PARSA_7 = 'PARSA_7'
    PARSA_8 = 'PARSA_8'
    DOLAKHA_1 = 'DOLAKHA_1'
    DOLAKHA_2 = 'DOLAKHA_2'
    RAMECHHAP_1 = 'RAMECHHAP_1'
    RAMECHHAP_2 = 'RAMECHHAP_2'
    SINDHULI_1 = 'SINDHULI_1'
    SINDHULI_2 = 'SINDHULI_2'
    SINDHULI_3 = 'SINDHULI_3'
    SINDHULI_4 = 'SINDHULI_4'
    RASUWA_1 = 'RASUWA_1'
    RASUWA_2 = 'RASUWA_2'
    DHADING_1 = 'DHADING_1'
    DHADING_2 = 'DHADING_2'
    DHADING_3 = 'DHADING_3'
    DHADING_4 = 'DHADING_4'
    NUWAKOT_1 = 'NUWAKOT_1'
    NUWAKOT_2 = 'NUWAKOT_2'
    NUWAKOT_3 = 'NUWAKOT_3'
    NUWAKOT_4 = 'NUWAKOT_4'
    KATHMANDU_1 = 'KATHMANDU_1'
    KATHMANDU_2 = 'KATHMANDU_2'
    KATHMANDU_3 = 'KATHMANDU_3'
    KATHMANDU_4 = 'KATHMANDU_4'
    KATHMANDU_5 = 'KATHMANDU_5'
    KATHMANDU_6 = 'KATHMANDU_6'
    KATHMANDU_7 = 'KATHMANDU_7'
    KATHMANDU_8 = 'KATHMANDU_8'
    KATHMANDU_9 = 'KATHMANDU_9'
    KATHMANDU_10 = 'KATHMANDU_10'
    KATHMANDU_11 = 'KATHMANDU_11'
    KATHMANDU_12 = 'KATHMANDU_12'
    KATHMANDU_13 = 'KATHMANDU_13'
    KATHMANDU_14 = 'KATHMANDU_14'
    KATHMANDU_15 = 'KATHMANDU_15'
    KATHMANDU_16 = 'KATHMANDU_16'
    KATHMANDU_17 = 'KATHMANDU_17'
    KATHMANDU_18 = 'KATHMANDU_18'
    KATHMANDU_19 = 'KATHMANDU_19'
    KATHMANDU_20 = 'KATHMANDU_20'
    BHAKTAPUR_1 = 'BHAKTAPUR_1'
    BHAKTAPUR_2 = 'BHAKTAPUR_2'
    BHAKTAPUR_3 = 'BHAKTAPUR_3'
    BHAKTAPUR_4 = 'BHAKTAPUR_4'
    LALITPUR_1 = 'LALITPUR_1'
    LALITPUR_2 = 'LALITPUR_2'
    LALITPUR_3 = 'LALITPUR_3'
    LALITPUR_4 = 'LALITPUR_4'
    LALITPUR_5 = 'LALITPUR_5'
    LALITPUR_6 = 'LALITPUR_6'
    KAVREPALANCHOWK_1 = 'KAVREPALANCHOWK_1'
    KAVREPALANCHOWK_2 = 'KAVREPALANCHOWK_2'
    KAVREPALANCHOWK_3 = 'KAVREPALANCHOWK_3'
    KAVREPALANCHOWK_4 = 'KAVREPALANCHOWK_4'
    SINDHUPALCHOWK_1 = 'SINDHUPALCHOWK_1'
    SINDHUPALCHOWK_2 = 'SINDHUPALCHOWK_2'
    SINDHUPALCHOWK_3 = 'SINDHUPALCHOWK_3'
    SINDHUPALCHOWK_4 = 'SINDHUPALCHOWK_4'
    MAKWANPUR_1 = 'MAKWANPUR_1'
    MAKWANPUR_2 = 'MAKWANPUR_2'
    MAKWANPUR_3 = 'MAKWANPUR_3'
    MAKWANPUR_4 = 'MAKWANPUR_4'
    CHITWAN_1 = 'CHITWAN_1'
    CHITWAN_2 = 'CHITWAN_2'
    CHITWAN_3 = 'CHITWAN_3'
    CHITWAN_4 = 'CHITWAN_4'
    CHITWAN_5 = 'CHITWAN_5'
    CHITWAN_6 = 'CHITWAN_6'
    GORKHA_1 = 'GORKHA_1'
    GORKHA_2 = 'GORKHA_2'
    GORKHA_3 = 'GORKHA_3'
    GORKHA_4 = 'GORKHA_4'
    MANANG_1 = 'MANANG_1'
    MANANG_2 = 'MANANG_2'
    LAMJUNG_1 = 'LAMJUNG_1'
    LAMJUNG_2 = 'LAMJUNG_2'
    KASKI_1 = 'KASKI_1'
    KASKI_2 = 'KASKI_2'
    KASKI_3 = 'KASKI_3'
    KASKI_4 = 'KASKI_4'
    KASKI_5 = 'KASKI_5'
    KASKI_6 = 'KASKI_6'
    TANAHUN_1 = 'TANAHUN_1'
    TANAHUN_2 = 'TANAHUN_2'
    TANAHUN_3 = 'TANAHUN_3'
    TANAHUN_4 = 'TANAHUN_4'
    SYANGJA_1 = 'SYANGJA_1'
    SYANGJA_2 = 'SYANGJA_2'
    SYANGJA_3 = 'SYANGJA_3'
    SYANGJA_4 = 'SYANGJA_4'
    NAWALPARASI_BARDAGHAT_SUSTA_EAST_1 = 'NAWALPARASI_BARDAGHAT_SUSTA_EAST_1'
    NAWALPARASI_BARDAGHAT_SUSTA_EAST_2 = 'NAWALPARASI_BARDAGHAT_SUSTA_EAST_2'
    NAWALPARASI_BARDAGHAT_SUSTA_EAST_3 = 'NAWALPARASI_BARDAGHAT_SUSTA_EAST_3'
    NAWALPARASI_BARDAGHAT_SUSTA_EAST_4 = 'NAWALPARASI_BARDAGHAT_SUSTA_EAST_4'
    MUSTANG_1 = 'MUSTANG_1'
    MUSTANG_2 = 'MUSTANG_2'
    MYAGDI_1 = 'MYAGDI_1'
    MYAGDI_2 = 'MYAGDI_2'
    BAGLUNG_1 = 'BAGLUNG_1'
    BAGLUNG_2 = 'BAGLUNG_2'
    BAGLUNG_3 = 'BAGLUNG_3'
    BAGLUNG_4 = 'BAGLUNG_4'
    PARBAT_1 = 'PARBAT_1'
    PARBAT_2 = 'PARBAT_2'
    GULMI_1 = 'GULMI_1'
    GULMI_2 = 'GULMI_2'
    GULMI_3 = 'GULMI_3'
    GULMI_4 = 'GULMI_4'
    PALPA_1 = 'PALPA_1'
    PALPA_2 = 'PALPA_2'
    PALPA_3 = 'PALPA_3'
    PALPA_4 = 'PALPA_4'
    ARGHAKHANCHI_1 = 'ARGHAKHANCHI_1'
    ARGHAKHANCHI_2 = 'ARGHAKHANCHI_2'
    NAWALPARASI_BARDAGHAT_SUSTA_WEST_1 = 'NAWALPARASI_BARDAGHAT_SUSTA_WEST_1'
    NAWALPARASI_BARDAGHAT_SUSTA_WEST_2 = 'NAWALPARASI_BARDAGHAT_SUSTA_WEST_2'
    NAWALPARASI_BARDAGHAT_SUSTA_WEST_3 = 'NAWALPARASI_BARDAGHAT_SUSTA_WEST_3'
    NAWALPARASI_BARDAGHAT_SUSTA_WEST_4 = 'NAWALPARASI_BARDAGHAT_SUSTA_WEST_4'
    RUPANDEHI_1 = 'RUPANDEHI_1'
    RUPANDEHI_2 = 'RUPANDEHI_2'
    RUPANDEHI_3 = 'RUPANDEHI_3'
    RUPANDEHI_4 = 'RUPANDEHI_4'
    RUPANDEHI_5 = 'RUPANDEHI_5'
    RUPANDEHI_6 = 'RUPANDEHI_6'
    RUPANDEHI_7 = 'RUPANDEHI_7'
    RUPANDEHI_8 = 'RUPANDEHI_8'
    RUPANDEHI_9 = 'RUPANDEHI_9'
    RUPANDEHI_10 = 'RUPANDEHI_10'
    KAPILVASTU_1 = 'KAPILVASTU_1'
    KAPILVASTU_2 = 'KAPILVASTU_2'
    KAPILVASTU_3 = 'KAPILVASTU_3'
    KAPILVASTU_4 = 'KAPILVASTU_4'
    KAPILVASTU_5 = 'KAPILVASTU_5'
    KAPILVASTU_6 = 'KAPILVASTU_6'
    EASTERN_RUKUM_1 = 'EASTERN_RUKUM_1'
    EASTERN_RUKUM_2 = 'EASTERN_RUKUM_2'
    ROLPA_1 = 'ROLPA_1'
    ROLPA_2 = 'ROLPA_2'
    PYUTHAN_1 = 'PYUTHAN_1'
    PYUTHAN_2 = 'PYUTHAN_2'
    DANG_1 = 'DANG_1'
    DANG_2 = 'DANG_2'
    DANG_3 = 'DANG_3'
    DANG_4 = 'DANG_4'
    DANG_5 = 'DANG_5'
    DANG_6 = 'DANG_6'
    BANKE_1 = 'BANKE_1'
    BANKE_2 = 'BANKE_2'
    BANKE_3 = 'BANKE_3'
    BANKE_4 = 'BANKE_4'
    BANKE_5 = 'BANKE_5'
    BANKE_6 = 'BANKE_6'
    BARDIYA_1 = 'BARDIYA_1'
    BARDIYA_2 = 'BARDIYA_2'
    BARDIYA_3 = 'BARDIYA_3'
    BARDIYA_4 = 'BARDIYA_4'
    SALYAN_1 = 'SALYAN_1'
    SALYAN_2 = 'SALYAN_2'
    DOLPA_1 = 'DOLPA_1'
    DOLPA_2 = 'DOLPA_2'
    MUGU_1 = 'MUGU_1'
    MUGU_2 = 'MUGU_2'
    JUMLA_1 = 'JUMLA_1'
    JUMLA_2 = 'JUMLA_2'
    KALIKOT_1 = 'KALIKOT_1'
    KALIKOT_2 = 'KALIKOT_2'
    HUMLA_1 = 'HUMLA_1'
    HUMLA_2 = 'HUMLA_2'
    JAJARKOT_1 = 'JAJARKOT_1'
    JAJARKOT_2 = 'JAJARKOT_2'
    DAILEKH_1 = 'DAILEKH_1'
    DAILEKH_2 = 'DAILEKH_2'
    DAILEKH_3 = 'DAILEKH_3'
    DAILEKH_4 = 'DAILEKH_4'
    SURKHET_1 = 'SURKHET_1'
    SURKHET_2 = 'SURKHET_2'
    SURKHET_3 = 'SURKHET_3'
    SURKHET_4 = 'SURKHET_4'
    WESTERN_RUKUM_1 = 'WESTERN_RUKUM_1'
    WESTERN_RUKUM_2 = 'WESTERN_RUKUM_2'
    BAJURA_1 = 'BAJURA_1'
    BAJURA_2 = 'BAJURA_2'
    ACHHAM_1 = 'ACHHAM_1'
    ACHHAM_2 = 'ACHHAM_2'
    ACHHAM_3 = 'ACHHAM_3'
    ACHHAM_4 = 'ACHHAM_4'
    BAJHANG_1 = 'BAJHANG_1'
    BAJHANG_2 = 'BAJHANG_2'
    DOTI_1 = 'DOTI_1'
    DOTI_2 = 'DOTI_2'
    KAILALI_1 = 'KAILALI_1'
    KAILALI_2 = 'KAILALI_2'
    KAILALI_3 = 'KAILALI_3'
    KAILALI_4 = 'KAILALI_4'
    KAILALI_5 = 'KAILALI_5'
    KAILALI_6 = 'KAILALI_6'
    KAILALI_7 = 'KAILALI_7'
    KAILALI_8 = 'KAILALI_8'
    KAILALI_9 = 'KAILALI_9'
    KAILALI_10 = 'KAILALI_10'
    DARCHULA_1 = 'DARCHULA_1'
    DARCHULA_2 = 'DARCHULA_2'
    BAITADI_1 = 'BAITADI_1'
    BAITADI_2 = 'BAITADI_2'
    DADELDHURA_1 = 'DADELDHURA_1'
    DADELDHURA_2 = 'DADELDHURA_2'
    KANCHANPUR_1 = 'KANCHANPUR_1'
    KANCHANPUR_2 = 'KANCHANPUR_2'
    KANCHANPUR_3 = 'KANCHANPUR_3'
    KANCHANPUR_4 = 'KANCHANPUR_4'
    KANCHANPUR_5 = 'KANCHANPUR_5'
    KANCHANPUR_6 = 'KANCHANPUR_6'


class House(models.TextChoices):
    HOUSE_OF_REPRESENTATIVES = 'HOUSE_OF_REPRESENTATIVES', 'House of Representatives'
    NATIONAL_ASSEMBLY = 'NATIONAL_ASSEMBLY', 'National Assembly'
    PROVINCE_ASSEMBLY = 'PROVINCE_ASSEMBLY', 'Province Assembly'

class ElectionYears(models.IntegerChoices):
    Y2026 = 2026, "2082"

class Representative(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    house = models.CharField(max_length=30, choices=House.choices,default="HOUSE_OF_REPRESENTATIVES")
    hor_constituency = models.CharField(max_length=50, choices=HoR_Constituency.choices, blank=True, null=True)
    province_constituency = models.CharField(max_length=50, choices=Province_Constituency.choices, blank=True, null=True)
    year = models.IntegerField(choices=ElectionYears.choices,default=2026)
    party = models.ForeignKey(Party, on_delete=models.CASCADE,null=True,blank=True)
    proportional = models.BooleanField(default=False)
    winner = models.BooleanField(default=False)
    order = models.IntegerField(blank=True,null=True)
    promise = models.TextField(blank=True, null=True)
    symbol = models.ImageField(upload_to=get_flag_image_path, null=True, blank=True, validators=[FileExtensionValidator(allowed_extensions=ALLOWED_IMAGE_EXTENSIONS), image_validate])
